apiVersion: v1
kind: List
items:
# Frontend Web App
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: org-capacity-app
    name: org-capacity-app-builder
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: org-capacity-app
    name: org-capacity-app
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: org-capacity-app
    name: org-capacity-app-builder
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: org-capacity-app-builder:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/abgov/org-capacity-prototype.git
        ref: master
      contextDir: .
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: OUTPUT_DIR
            value: dist/apps/org-capacity-app
          - name: NPM_BUILD
            value: npm run nx build org-capacity-app -- --configuration=production
        from:
          kind: DockerImage
          name: nodeshift/ubi8-s2i-web-app:latest
        incremental: true
      type: Source
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: org-capacity-app
    name: org-capacity-app
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: org-capacity-app:latest
    postCommit: {}
    resources: {}
    source:
      type: Image
      images:
        - from:
            kind: ImageStreamTag
            name: org-capacity-app-builder:latest
          paths:
            - destinationDir: .
              sourcePath: /opt/app-root/output/.
            - destinationDir: .
              sourcePath: /tmp/src/nginx.conf
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: centos/nginx-112-centos7:latest
        incremental: true
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: org-capacity-app-builder:latest
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: org-capacity-app
    name:  org-capacity-app-config
  data:
    environment: |-
      {
          "production": true,
          "API_URL": "/api",
          "GRAPH_API_URL": "/api/capacity/v1/graphql",
          "AUTH_URL": "",
          "AUTH_CLIENT_ID": "org-capacity-app"
      }
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: org-capacity-app
    name: org-capacity-app
  spec:
    replicas: 1
    selector:
      app: org-capacity-app
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: org-capacity-app
      spec:
        containers:
        - image: org-capacity-app
          imagePullPolicy: IfNotPresent
          name: org-capacity-app
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          volumeMounts:
            - mountPath: /opt/app-root/src/config
              name: config-volume
              readOnly: true
        volumes:
        - configMap:
            items:
              - key: environment
                path: environment.json
            name: org-capacity-app-config
          name: config-volume
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - org-capacity-app
          from:
            kind: ImageStreamTag
            name: org-capacity-app:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: org-capacity-app
    name: org-capacity-app
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: org-capacity-app
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: org-capacity-app
    name: org-capacity-app
  spec:
    port:
      targetPort: 8080
    tls:
      termination: edge
    to:
      kind: Service
      name: org-capacity-app

# Backend service
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: org-capacity-service
    name: org-capacity-service
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: org-capacity-service
    name: org-capacity-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: org-capacity-service:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/abgov/org-capacity-prototype.git
        ref: master
      contextDir: .
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: centos/nodejs-12-centos7:latest
        incremental: true
      type: Source
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: org-capacity-service
    name: org-capacity-service
  spec:
    replicas: 1
    selector:
      app: org-capacity-service
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: org-capacity-service
      spec:
        containers:
        - env:
            - name: NPM_RUN
              value: 'service'
            - name: KEYCLOAK_ROOT_URL
              value: ''
            - name: KEYCLOAK_REALM
              value: capacity
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  key: database_name
                  name: ''
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: ''
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ''
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: ''
            - name: LOG_LEVEL
              value: info
            - name: port
              value: '3333'
          image: org-capacity-service
          imagePullPolicy: IfNotPresent
          name: org-capacity-service
          ports:
          - containerPort: 3333
            name: http
            protocol: TCP
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - org-capacity-service
          from:
            kind: ImageStreamTag
            name: org-capacity-service:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: org-capacity-service
    name: org-capacity-service
  spec:
    ports:
    - name: http
      port: 3333
      targetPort: 3333
    selector:
      app: org-capacity-service
